- name: Include variables from users.test
  include_vars:
    file: ../../../dummy/users.test

- name: Debug information
  debug:
    var: users

- name: Debug information
  debug:
    msg: "{{ item }}"
  loop: "{{ users }}"

- name: Debug information
  debug:
    msg: "{{ item.name }}"
  loop: "{{ users }}"
